// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add
// one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */

var findTheDifference = function(s, t) {
  let sArr = s.split('').sort();
  let tArr = t.split('').sort();

  for (let i = 0; i < sArr.length; i++) {
    if (sArr[i] !== tArr[i]) {
      return tArr[i];
    }
  }

  return tArr[tArr.length - 1];
};

// Time Complexity - O(s)
// Space Complexity - O(s + t)
// s = number of chars in s
// t = number of chars in t
