# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add
# one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#   Input:
#     s = "abcd"
#     t = "abcde"
#
#     Output:
#       e
#
# Explanation:
# ' e' is the letter that was added.

# param {String} s
# param {String} t
# return {Character}

def find_the_difference(s, t)
  s_sorted = s.sort
  t_sorted = t.sort

  (0...t_sorted.length).each do |i|
    if t_sorted[i] != s_sorted[i]
      return t_sorted[i]
    end
  end
end

# Time Complexity - O(tlogt), where t = t.length
# Space Complexity - O(s+t), where s and t = length
